#!/bin/bash
BIOBASH_HOME=$1

BIOBASH_LIB="$BIOBASH_HOME/lib"
SHML_LIB="$BIOBASH_LIB/shml/shml.sh" 
BASHUTILITY_LIBPATH="$BIOBASH_LIB/bash-utility"
BASHUTILITY_LIB="$BASHUTILITY_LIBPATH/bash_utility.sh"

touch env.sh

#Create the actual env.sh file

echo "
BIOBASH_HOME="$BIOBASH_HOME"
BIOBASH_LIB="$BIOBASH_LIB" 
SHML_LIB="$SHML_LIB"
BASHUTILITY_LIBPATH="$BASHUTILITY_LIBPATH"
BASHUTILITY_LIB="$BASHUTILITY_LIB"

source $BASHUTILITY_LIB
source $SHML_LIB

#export PATH=$PATH:$BIOBASH_HOME
#export PATH=$PATH:$BIOBASH_LIB
#export PATH=$PATH:$SHML_LIB
#export PATH=$PATH:$BASHUTILITY_LIBPATH
#export PATH=$PATH:$BASHUTILITY_LIB
" > env.sh
