#!/bin/bash
#
# Performs the installation of BIOBASH.
#

# We are assuming a standard installation on a Linux Machine (at least
# for now). This is the default directory for installation.
default="/usr/local/bin"

# Some propaganda/user feedback.
echo "

#
            BIOBASH INSTALLATION
Bioinformatics and Systems Biology Laboratory
            Institute for Genetics
        National University of Colombia
#


"
#Use this message if something goes wrong.
failure=" == WARNING! Unable to install BIOBASH =="

BBVERSION=$(cat version)

echo  "Hit ENTER to use the default installation directory ($default) or provide a
valid installation path below:"
read -p " > " dir

#If user hitted ENTER, $dir comes empty, so use default install dir.
#Otherwise use user provided path.
if [ -z "$dir" ]; then

    installDir=$default
    
else
    installDir=$dir
fi


#A BETTER SOLUTION HERE IS CHECK THAT DIRECTORY DO NOT EXIST AND THEN EXIT:
# https://www.linuxquestions.org/questions/linux-newbie-8/check-if-directory-does-not-exist-in-bash-806969/


#Wether install will be performed on user defined or default install dir, it is
# important to make sure that it exists and that we can write on it.
# Does it exist?
if [ -d "$installDir" ];then
    
    # Is it writable?
    if [ -w "$installDir" ];then
	
       #-----------------------------------------
       # MAIN INSTALLATION
       #-----------------------------------------

        BIOBASH_HOME=$(echo $installDir/$BBVERSION)
        echo "Installing to: $BIOBASH_HOME"
	mkdir $BIOBASH_HOME

 	#Check pre-requisites
	# gcc, zlib, wget or curl, unzip, EMBOSS.
	./check_dependencies.sh

	# install seqtk
	./install_seqtk.sh

	# This routine puts all needed variables into bashrc
	./setup_environment.sh $BIOBASH_HOME

	#Future version need a better selection of what to install.
        cp -r ./lib $BIOBASH_HOME
        cp -r ./bin $BIOBASH_HOME
        cp -r ./tmp $BIOBASH_HOME
        cp *.sh ./lib $BIOBASH_HOME


        echo "Installation complete. Thank you for installing BIOBASH
        
        "
    else

    
    echo $failure
    echo " "
    echo "$installDir is not writable.Please make sure you have write access."
    echo "  "

    fi
    
else
    echo $failure
    echo "  "
    echo "  The directory you just typed ($installDir) does not exist."
    echo "  Please make sure route is correct"
    echo " "
fi

