#!/bin/bash
#
# Performs the installation of BIOBASH.
#

#Common libraries
source lib/shml/shml.sh
source lib/bash-utility/src/interaction.sh


#----------------------------------------------------------------------------
#
#  FUNCTIONS
#
#----------------------------------------------------------------------------

# Reads user input to define installation directory. Returns real path to dir.
function define_install_dir() {
    read -p "Install in (/usr/local): " dir

    #If user hitted ENTER, $dir comes empty, so use default install dir.
    #Otherwise use user provided path.
    if [ -z "$dir" ]; then
        dir=$default
    else
        dir=$dir
    fi
    #realpath for installDir. No relative paths allowed.
    #There is a bug with paths like "~/path/to/dir". For some reason "realpath" do not
    #resolve this type of path in the script, but it does in the shell!!??
    return=$(realpath ${dir})
    
    #Return value
    echo "$return"
}




# Some propaganda/user feedback.
echo "

$(fgcolor green '                 = BIOBASH INSTALLER =') $(fgcolor end)       
$(fgcolor green '         Bioinformatics and Systems Biology Laboratory') $(fgcolor end)
$(fgcolor green '   Institute for Genetics -  National University of Colombia') $(fgcolor end)
"

#----------------------------------------------------------------------------
#
#  BEFORE ATTEMPTING ANYTHING... check pre-requisites.
#
#----------------------------------------------------------------------------
./check_dependencies.sh

#If check dependencies was succesful it creates a "flag" file: depend_ok
#otherwise (file doesn`t exist) there are dependencies to be met. Stop installation.
if [[ ! -e depend_ok ]];then
	
	echo "Quitting installation of BioBash.
	"
	exit 1
fi

# If we reached this point it means dependencies check was succesful and therefore
# it is safe to erase depend_ok file. It is not needed from now on.
rm depend_ok




#----------------------------------------------------------------------------
#
#          START ACTUAL INSTALLATION
#
#-----------------------------------------------------------------------------

# We are assuming a standard installation on a Linux Machine (at least
# for now). This is the default directory for installation.
default="/usr/local"


echo " Initiating BioBash installation."
echo "$(hr)"

echo  "
The installation directory is the place where all BioBash related files will be stored,
including libraries and binaries. By default BioBash will be installed in '$default' directory,
nevertheless you need write permissions on that folder. Alternatively you can define  a
path to another installation directory.
Hit ENTER to use the default installation directory ($default) or provide a
valid installation path:
"

installDir="$(define_install_dir)"
echo $installDir

exit 0

# Wether install will be performed on user defined or default install dir, it is
# important to make sure that it exists and that we can write on it.
# Does it exist?
if [ ! -d "${installDir}" ];then
    
    exists=0
	echo 
	"$installDir does not exist. Please make sure it is a valid directory.
	"
	
	until [ $exists  == "y" ]
    do
        #keep asking for a valid directory
	    installDir="$(define_install_dir)"
    done
fi

# If we reached this point it means directoy exists. Check if it is writable.
if [ ! -w "$installDir" ];then
	echo "I can not write to: $installDir. Please make sure you have the right permissions on that folder."
	exit 1

fi


#If we reached this point, it means we can proceed with installation. 
#-----------------------------------------
# MAIN INSTALLATION
#-----------------------------------------



#This is KEY. Everything will be referenced to this path.
BBVERSION=$(cat version)
BIOBASH_HOME=$(echo $installDir/$BBVERSION)

#User feedback
echo "Installing to: $BIOBASH_HOME"

#Create BIOBASH directory. The "-p" option is useful when re-trying the installation multiple times,
#so if the directory was created before it won't complain because directory already exists.
mkdir -p $BIOBASH_HOME


	# install seqtk
	#./install_seqtk.sh

	# This routine puts all needed variables into bashrc
	# This script reads the $1 var.
	./setup_environment.sh $BIOBASH_HOME

	# Future version need a better selection of what to install.
    #    cp -r ./lib $BIOBASH_HOME
    #    cp -r ./bin $BIOBASH_HOME
    #    cp -r ./tmp $BIOBASH_HOME
    #    cp *.sh ./lib $BIOBASH_HOME


  echo "Installation complete. Thank you for installing BIOBASH"
  exit 0

